pkg/builder/docsonnet/docsonnet.go, pkg/builder/objects.go, pkg/builder/primitives.go, pkg/model/gvk.go, pkg/model/modifiers.go, pkg/render/modifiers.go, pkg/render/render.go, pkg/render/sort.go, pkg/render/sort_test.go
Implements an initial draft of [docsonnet](https://github.com/sh0rez/docsonnet) generation. Seems to work, yet not complete. Missing:
=> feat(gen): docsonnet

custom/mapContainers.libsonnet
* cronJobs are in `v1beta1` not `v1` 
* they have an extra wrapper of `jobTemplate.spec` for the container definition.
There might be a cleaner way to implement this, but this is working for me locally
=> Fix mapContainers for cronJob

custom/mapContainers.libsonnet
Refactors mapContainers so all implementations share the same docsonnet
=> doc: job.mapContainers docsonnet

custom/apps.libsonnet, custom/batch.libsonnet, custom/core.libsonnet, custom/rbac.libsonnet
This adds a bunch of functions inspired by https://github.com/grafana/jsonnet-libs/blob/0f9b4bbce38addc30035e748b50b5fe41cac468c/ksonnet-util/kausal.libsonnet
Best reviewed as individual commits.
=> feat: extend custom

custom/core/rbac.libsonnet
A proposal for #15
```
cluster_role: clusterRole.new($.name),
cluster_role_binding:
clusterRoleBinding.new($.name)
+ clusterRoleBinding.bindRole($.cluster_role),
```
=> feat(custom): add bindRole shortcut

custom/core/apps.libsonnet
=> fix(custom): allow overriding podLabels

custom/core/autoscaling.libsonnet
=> fix: add withApiVersion for crossVersionObjectReference

pkg/builder/objects_test.go, pkg/builder/primitives.go
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>
=> feat: Add FloatType

custom/core/apps.libsonnet, custom/core/volumeMounts.libsonnet
These are helper functions that have been battle tested in ksonnet-util for a long time and proven quite useful.
ref: https://github.com/grafana/jsonnet-libs/blob/master/ksonnet-util/util.libsonnet#L102
Fixed typo along the way.
=> feat: add volumeMounts helper functions

.github/workflow/main.yml
This is to enable github actions on PRs too.
=> Add dummy github action

.github/workflows/main.yml, jsonnet/github_action.jsonnet
I've created a separate jsonnet-libs-bot user and a personal access token. I hope this is
enough to create new repositories.
=> fix(github-action): execute TF with Personal Access Token

Dockerfile, Makefile
=> fix(github-actions): add ssh client

.github/workflows/main.yml, jsonnet/github_action.jsonnet, scripts/configure_github_ssh.sh
=> fix(github-action): cannot clone without host key verification

.github/workflows/main.yml, Makefile, bin/docker.sh, jsonnet/github_action.jsonnet, scripts/configure_github_ssh.sh, scripts/gen.sh
=> fix(github-action): configure ssh in container

.github/workflows/main.yml, libs/strimzi/config.jsonnet, pkg/builder/objects.go, pkg/model/modifiers.go
=> feat(lib): add strimzi library and fix dash prefix in args

.github/workflows/main.yml, jsonnet/config.jsonnet
Forgot that, should create a pre-commit hook for that.
=> fix(ci): include kube-prometheus in github workflow

libs/crossplane/config.jsonnet
=> feat(crossplane): add provider-sql

README.md, jsonnet/config.jsonnet, libs/argo-workflows/config.jsonnet, libs/cert-manager/config.jsonnet, libs/cnrm/config.jsonnet, libs/crossplane/config.jsonnet, libs/flagger/config.jsonnet, libs/istio/config.jsonnet, libs/kube-prometheus/config.jsonnet, libs/strimzi/config.jsonnet, scripts/bare-k3s, scripts/gen.sh
Essentially, this runs one k3s cluster per version
Ports for each cluster are incremented in the for loop
Tested with strimzi
Fixes #60
=> Support multiple version of libraries from CRDs

scripts/gen.sh
It's not really waiting for reconciliation right now
=> Fix logic error

libs/crossplane/config.jsonnet, pkg/builder/objects.go, pkg/model/modifiers.go
Supersedes https://github.com/jsonnet-libs/k8s/pull/56
=> Bump crossplane verions and fix reserved function keyword

.github/workflows/main.yml, libs/rabbitmq/config.jsonnet, scripts/gen.sh
=> feat(lib): add library for rabbitmq-operator objects

.github/workflows/main.yml, libs/fluxcd/config.jsonnet
Defines library for version 0.17.2 of https://github.com/fluxcd/flux2
=> Add FluxCD v2 templates

libs/istio/config.jsonnet
Add more versions for istio, these are the versions that we think it
is commonly still in use.
=> Support more versions of istio

.github/workflows/main.yml, libs/grafana-agent/config.jsonnet
Adds generation for Grafana Agent CRDs (https://github.com/grafana/agent/)
=> Add Grafana Agent

libs/flagger/config.jsonnet
Supersedes: https://github.com/jsonnet-libs/k8s/pull/94
=> Add Flagger 1.16

libs/crossplane/config.jsonnet
=> feat(crossplane): add provider-azure 0.18

.gitignore, libs/external-secrets/config.jsonnet
also sneeked in a gitignore fix :innocent:
=> feat: add external-secrets

.github/workflows/main.yml, libs/crossplane/config.jsonnet
=> feat(crossplane): add kubernetes + update/add latest for others

pkg/builder/marshal.go, pkg/builder/objects_test.go, pkg/builder/primitives.go
=> Support null on builder

.github/workflows/main.yml, libs/grafana-operator/config.jsonnet, pkg/builder/objects.go
Adds generation for Grafana Operator CRDs:
https://github.com/grafana-operator/grafana-operator/
This required a small change to field escaping, since various properties
contain a `.` character, such as `Grafana.spec.config.['auth.basic']`
=> Add Grafana Operator

.github/workflows/main.yml, libs/crossplane/config.jsonnet
I ran `make configure` and got an unexpected diff, I assume the file was manually changed.
=> feat(lib): add Crossplane 1.6 and provider-aws 0.23

libs/cert-manager/config.jsonnet
Add an output for the highest available patch version of each minor
version
=> cert-manager: support each minor version >=1.3

.github/workflows/main.yml, libs/argo-cd/config.jsonnet
Add argo-cd CRDs
https://github.com/argoproj/argo-cd
=> Add argo-cd CRDs

jsonnet/terraform.jsonnet
Pulling the previous version failed on master.
=> fix(tf): update github provider

libs/external-secrets/config.jsonnet
=> update(external-secrets): to 0.4.4

libs/crossplane/config.jsonnet
=> feat(crossplane): add provider-jet-gcp

libs/crossplane/config.jsonnet
Title says it, generate lib for https://github.com/grafana/crossplane-provider-grafana
=> feat(crossplane): add grafana provider

libs/actions-runner-controller/config.jsonnet
Adds the latest version of the actions-runner-controller.
=> Add github actions-runner-controller v0.21.1

libs/actions-runner-controller/config.jsonnet
Adds the latest version of the actions-runner-controller.
=> Add github actions-runner-controller v0.22.0

.github/workflows/main.yml, libs/composable/config.jsonnet, libs/composable/custom/helpers/ibmcloud.libsonnet
=> feat: add composable library

.github/workflows/main.yml, libs/banzai-logging/config.jsonnet
Hi folks,
I added support for banzai logging operator crds. All but the "logging.banzaicloud.io_loggings.yaml" had some issues, which I have skipped for now. Kindly review and merge to upstream.
=> feat: add banzai logging operator support

jsonnet/config.jsonnet
Jinja 3.1.0 triggers a bug: https://github.com/mkdocs/mkdocs/issues/2799
=> fix(mkdocs): pin jinja==3.0.0

libs/external-secrets/config.jsonnet
New version, has some breaking changes.
=> feat(libs): add ESO 0.5.x

libs/crossplane/config.jsonnet, libs/crossplane/custom/crossplane/compositeResourceDefinition.libsonnet, libs/crossplane/custom/crossplane/composition.libsonnet, libs/crossplane/custom/crossplane/resource.libsonnet
We've been using these functions internally for a while, it is about time we'd document
and open source them.
=> feat(crossplane): extend crossplane lib with various helper functions

libs/crossplane/custom/crossplane/compositeResourceDefinition.libsonnet, libs/crossplane/custom/crossplane/composition.libsonnet, libs/crossplane/custom/crossplane/resource.libsonnet
Some tweaks that came up after refactoring the internal libs to use this.
=> feat(crossplane): fix docstrings & use singular

.github/workflows/main.yml, libs/aws-load-balancer-controller/config.jsonnet
From https://github.com/kubernetes-sigs/aws-load-balancer-controller
=> Add aws-load-balancer-controller

libs/k8s/custom/core/batch.libsonnet
Add the custom batch/CronJob patch to v1.
=> Add CronJob patch to v1

.github/workflows/main.yml, libs/kyverno/config.jsonnet
CRDs retrieved from https://github.com/kyverno/kyverno/blob/v1.6.2/config/crds/kustomization.yaml
=> Add Kyverno 1.6.2

libs/k8s/custom/core/core.libsonnet
This should resolve issue #80 .
=> Add newWithoutSelector constructor for Service objects

libs/k8s/custom/core/core.libsonnet
This should resolve the remaining comment by @Duologic from #166 .
=> Add docs for Service.newWithoutSelector

libs/k8s/config.jsonnet
fixes https://github.com/jsonnet-libs/k8s/issues/172
=> feat: add k8s 1.24, deprecate 1.18

.github/workflows/main.yml, libs/kubevela/config.jsonnet
add kubevela crds from https://github.com/kubevela/kubevela/tree/master/charts/vela-core/crds
Please kindly review.
=> feat: add kubevela v1.4.1

.github/workflows/main.yml, libs/vertical-pod-autoscaler/config.jsonnet, libs/vertical-pod-autoscaler/custom/core/autoscaling.libsonnet
Add auto-generation for [vertical-pod-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler) jsonnet.
=> Add vertical-pod-autoscaler

libs/k8s/custom/core/core.libsonnet, libs/k8s/custom/core/volumeMounts.libsonnet
- port in k.util.resources{Limits,Requests}
- introduce secretVolumeMountAnnotated from https://github.com/grafana/jsonnet-libs/pull/770
=> feat(k8s): add more ksonnet-util functions

libs/k8s/custom/core/autoscaling.libsonnet
=> Fix HPA `withScaleTargetRef` custom function

.github/workflows/main.yml, libs/litmus-chaos/config.jsonnet, pkg/builder/objects.go
* Adds configuration to generate libs for litmus-chaos CRDs, versions 2.8.0, 2.9.0 and 2.10.0.
* jsonnet-libs/k8s/issues/185 Fixes issue with keys containing forward slashes.
=> Add lib for litmus-chaos CRDs

libs/harbor-operator/config.jsonnet
https://github.com/goharbor/harbor-operator
=> Add harbor operator 

.github/workflows/main.yml
=> chore: make configure

.github/workflows/main.yml, libs/aiven/config.jsonnet
https://github.com/aiven/aiven-operator/releases/tag/v0.4.0
=> aiven add 0.4.0 suuport

Makefile, pkg/render/render.go
This need to be flipped, we're setting this for cluster resources.
=> fix(render): set namespaced to false for cluster resource

libs/argo-cd/config.jsonnet
* more flexible config for argo-cd
* updated patch versions of argo-cd
* `2.2.8` -> `2.2.12`
* `2.3.3` -> `2.3.7`
* added argo-cd `2.4.11`
=> Argocd update

libs/crossplane/config.jsonnet
=> feat(crossplane): add provider-jet-aws

libs/cert-manager/config.jsonnet
Update cert-manager to the latest version.
=> Update cert-manager to version 1.9.1

libs/fluxcd/config.jsonnet
Do we want to deprecate / remove some of the older versions here now?
=> Add FluxCD v0.32 / v0.33 / v0.34 / v0.35

.github/workflows/main.yml, jsonnet/github_action.jsonnet, libs/secrets-store-csi-driver/config.jsonnet
I am not 100% sure if this is "in-scope" for this project but we would like to have a jsonnet wrapper for secrets-store-csi resources. If there is another way to do this any hint would be really appreciated :)
Thanks!
=> add secrets-store-csi-driver to libs

libs/k8s/custom/core/core.libsonnet, libs/k8s/custom/core/volumeMounts.libsonnet
We added 2 helper functions to ease working with csi driver volumes.
Maybe that is something that would also benefit others.
=> add k8s csi volume mount custom functions

libs/k8s/custom/core/apps.libsonnet
=> fix: bug when using replicas=null on deployment creation

libs/aiven/config.jsonnet
=> updated aiven

libs/argo-cd/config.jsonnet
=> updated argo-cd

libs/aws-load-balancer-controller/config.jsonnet
Extracted versions table, bumped 2.4.6 version.
=> updated aws-load-balancer-controller

libs/banzaicloud-bank-vaults/config.jsonnet
=> updated banzaicloud-bank-vaults

libs/banzai-logging/config.jsonnet
=> updated banzai-logging

libs/calico/config.jsonnet
=> updated calico

libs/cert-manager/config.jsonnet
=> updated cert-manager

libs/cilium/config.jsonnet
=> updated cilium

libs/cluster-api-provider-aws/config.jsonnet
Added 1.3 1.4 1.5 2.0 versions and a versions table.
=> updated cluster-api-provider-aws

libs/contour/config.jsonnet
Added 1.21 1.22 1.23 versions.
=> updated contour

libs/grafana-agent/config.jsonnet
Bumped 0.26 snapshot version.
Added 0.30 version.
=> updated grafana-agent

libs/flagger/config.jsonnet
Added 1.25 1.26 1.27 versions.
=> updated flagger

libs/fluxcd/config.jsonnet
Added 0.36.0 0.37.0 0.38.3  versions.
Didn't extract the versions table due to CRDs being versioned directly in Kustomize.
=> updated fluxcd

libs/eck-operator/config.jsonnet
=> updated eck-operator

libs/argo-workflows/config.jsonnet
=> updated argo-workflows

libs/k8s/custom/core/autoscaling.libsonnet
=> `autoscaling/v2` is a thing

libs/zalando-postgres-operator/config.jsonnet
=> updated zalando-postgres-operator

libs/vertical-pod-autoscaler/config.jsonnet
=> updated vertical-pod-autoscaler

libs/securecodebox/config.jsonnet
=> updated securecodebox

libs/rabbitmq-messaging-topology-operator/config.jsonnet
=> updated rabbitmq-messaging-topology-operator

libs/kubevela/config.jsonnet
=> updated kubevela

libs/kubernetes-nmstate/config.jsonnet
=> updated kubernetes-nmstate

libs/crossplane/config.jsonnet
Also, add the new `azuread` official provider
=> Crossplane: Update upbound providers + Grafana

.github/workflows/main.yml, libs/traefik/config.jsonnet
I use a rather old version of traefik in my home lab, so that older version is included.
This also includes the latest version.
=> Add a traefik library

libs/contour/config.jsonnet
Adds latest Project Contour release: [v1.24](https://github.com/projectcontour/contour/releases/tag/v1.24.2)
=> Add Contour v1.24

libs/crossplane/config.jsonnet, libs/crossplane/custom/crossplane/resource.libsonnet
Documented here: https://docs.crossplane.io/v1.11/concepts/composition/#transform-types 
This new transform will be very useful for more complex cases
=> Crossplane: Support 1.11 + new `match` transform

libs/crossplane/config.jsonnet
Grafana Provider 0.5.0 + Crossplane 1.12
=> Update Crossplane versions

pkg/model/modifiers.go
I've encoutered a CRD with a `status` field but it's not being generated
=> Do not exclude the `status` attribute

.github/workflows/main.yml, libs/gatekeeper/config.jsonnet
https://github.com/open-policy-agent/gatekeeper/
=> libs: Add OPA Gatekeeper library

libs/gatekeeper/config.jsonnet
I had copy-pasted from external-secrets and not updated that bit. These are the CRDs from gatekeeper's repo.
=> gatekeeper: Fix CRD names

libs/grafana-operator/config.jsonnet
Refactor and add missing versions from v4.4 to the latest v5.0
=> chore(grafana-operator): refactor and add versions

libs/cert-manager/config.jsonnet
Adds latest cert-manager release.
=> Add cert-manager 1.12

libs/crossplane/custom/crossplane/resource.libsonnet
[Documented upstream here][docs].
[docs]: https://docs.crossplane.io/latest/concepts/composition/#transform-types
=> crossplane: Add string type transforms

.github/workflows/main.yml, libs/cloudnative-pg/config.jsonnet
This PR adds configuration to generate a Jsonnet library for [the Cloudnative-PG operator. ](https://github.com/cloudnative-pg/cloudnative-pg)
=> Add Cloudnative-PG Jsonnet library

libs/grafana-operator/config.jsonnet, libs/keda/config.jsonnet
- keda: add 2.11 version and indent jsonnet
- grafana-operator: bump latest version to 5.0.2
=> Update keda and grafana operator

libs/external-secrets/config.jsonnet
And add the generators to new versions
=> Update external-secrets versions

libs/fluxcd/config.jsonnet
Hooray for it being [made GA](https://fluxcd.io/blog/2023/07/flux-ga/)!
=> Add Flux 2.0.1

libs/actions-runner-controller/config.jsonnet
New release while the other PR was still open 😬
=> Add actions-runner-controller 0.5

libs/edp-keycloak-operator/config.jsonnet
The PR adds version 1.17.0 to edp-keycloak-operator.
=> chore(keycloak-edp): Add version 1.17.0

.github/workflows/main.yml, libs/vault-secrets-operator/config.jsonnet
Add configuration to generate a Jsonnet library for [Vault Secrets Operator (VSO)](https://github.com/hashicorp/vault-secrets-operator)
=> Add support for Vault Secrets Operator (VSO) jsonnet library

libs/external-secrets/config.jsonnet
Missed this when I bumped yesterday
=> external-secrets: Add PushSecret

libs/kube-prometheus/config.jsonnet
It includes two new CRDs added to v0.13:
- Prometheus Agent
- Scrape Config
=> Add kube-prometheus v0.13

libs/edp-keycloak-operator/config.jsonnet
The PR adds version 1.18.1 of edp-keycloak-operator.
=> chore(keycloak-edp): Add version 1.18.1

libs/vault-secrets-operator/config.jsonnet
https://github.com/hashicorp/vault-secrets-operator/blob/main/CHANGELOG.md#030-september-27th-2023
=> add new 0.3.0 vault-secrets-operator version

.github/workflows/main.yml, libs/external-dns/config.jsonnet
external-dns has an optional CRD source mechanism for creating DNS records.
https://github.com/kubernetes-sigs/external-dns/blob/v0.13.6/docs/contributing/crd-source.md
=> Add external-dns 0.13.6

libs/consul/config.jsonnet
Add new 1.3.1 consul-k8s version and also add missing crds for 0.34.
=> Add new 1.3 consul-k8s version

libs/consul/config.jsonnet
Unfortunately I broke the CI with #378 :pray:
=> fix: move the url definition in the for loop

.github/workflows/main.yml, libs/google-cloud-sql-proxy-operator/config.jsonnet
Update the crds for google cloud sql proxy operator to 1.4.2.
=> Update google-cloud-sql-proxy-operator to 1.4.2

libs/cloudnative-pg/config.jsonnet
See the [docs](https://cloudnative-pg.io/docs/).
=> bump CNPG library to the latest version

libs/cert-manager/config.jsonnet
Also bump 1.13 and 1.12 to their latest patch versions.
=> Add cert-manager 1.14

libs/gateway-api/config.jsonnet
I couldn't find out why it fails
=> Add gateway-api 0.8.1 and 1.0.0 versions

.github/workflows/main.yml, libs/envoy-gateway/config.jsonnet
Envoy Gateway does not exist as a jsonnet-lib but it is desired.
Add latest version of Envoy Gateway (v0.6.0)
=> chore: Add envoy-gateway

.github/workflows/main.yml, libs/knative-eventing/config.jsonnet, libs/knative-serving/config.jsonnet, libs/knative-serving/custom/serving/mapContainers.libsonnet, libs/triggermesh/config.jsonnet
Add CRDs for [Knative Serving](https://knative.dev/docs/serving/), [Knative Eventing](https://knative.dev/docs/eventing/) and [Triggermesh](https://www.triggermesh.com).
=> feat: Add knative-eventing, knative-serving and triggermesh CRDs

libs/prometheus-operator/config.jsonnet
Add new prometheus-operator versions. 
See https://github.com/prometheus-operator/prometheus-operator/releases
=> (feat) Add new prometheus-operator versions

libs/cloudnative-pg/config.jsonnet
That PR introduces the major release v1.23.0 and minor patches for v1.22 and v1.21.
=> Bump CNPG v1.23.1

.github/workflows/main.yml, libs/spicedb-operator/config.jsonnet
Adds a library for the [spicedb-operator](https://github.com/authzed/spicedb-operator) project.
=> Add spicedb-operator

libs/envoy-gateway/config.jsonnet
The GA version of Envoy Gateway has been released.
Add version `v1.0.1`
=> chore: Add latest version of Envoy Gateway (v1.0.1)

libs/contour/config.jsonnet
Adds latest Project Contour release: [v1.29.0](https://github.com/projectcontour/contour/releases/tag/v1.29.0)
=> Add Contour v1.29

libs/kyverno/config.jsonnet
=> feat: Add kyverno 1.12

libs/clickhouse-operator/config.jsonnet
New: Add the [clickhouse-operator](https://github.com/Altinity/clickhouse-operator) from Altinity.
=> Add clickhouse-operator from Altinity

libs/vault-secrets-operator/config.jsonnet
This adds v0.4-v0.7 versions of vault secrets operator (VSO).
=> Add newer versions of VSO

libs/karpenter/config.jsonnet
Also fix URL for renamed GitHub repo
=> feat: Add Karpenter 0.37, 1.0

libs/keda/config.jsonnet
I also dropped some older versions.
=> Add Keda 2.14+ and 2.15+

libs/cert-manager/config.jsonnet, libs/cilium/config.jsonnet
=> Update cert manager to 1.15.3 and cilium to 1.16.1

libs/grafana-operator/config.jsonnet
Bump 5.8 and add versions 5.9 to 5.14.
=> chore(grafana-operator): update versions

libs/kube-prometheus/config.jsonnet
=> Add kube-prometheus v0.14

.github/workflows/main.yml, libs/amazon-vpc-resource-controller/config.jsonnet
=> feat: Add amazon-vpc-resource-controller

libs/vault-secrets-operator/config.jsonnet
=> feat: Add vault-secrets-operator 0.8

libs/calico/config.jsonnet
=> Update calico version and include new CRD

libs/minio-operator/config.jsonnet
- **Add minio-operator 6.0.0, fix prefix**
- **fix(minio-operator): reduce number of patch releases**
rebased #435
=> minio operator

.github/workflows/main.yml, libs/metallb/config.jsonnet
=> Add metallb CRDs

libs/cloudnative-pg/config.jsonnet
See the latest [releases](https://cloudnative-pg.io/docs/).
=> Update CloudnativePG operator

libs/crossplane/config.jsonnet
=> Crossplane 1.16 and 1.17

libs/fluxcd/config.jsonnet
Adding fluxcd 2.4.0 CRDs mappings
=> Add fluxcd v2.4.0 library

libs/aws-load-balancer-controller/config.jsonnet
Adds the latest release of the aws-load-balancer-controller
=> Add v2.11.0 release of aws-load-balancer-controller

libs/k8s/config.jsonnet
remove 1.26 and 1.27
add 1.31 and 1.32
=> Update to the latest versions of k8s

libs/keda/config.jsonnet
=> chore(keda): update versions

.github/workflows/main.yml, libs/grafana-alloy/config.jsonnet
This commit adds the Grafana Alloy (https://github.com/grafana/alloy/) CRDs in version 1.6.1.
=> feat(grafana-alloy): add Grafana Alloy

libs/victoria-metrics-operator/config.jsonnet
Libs for the victoria-metrics CRDs (Version 0.30-0.50)
=> victoria-metrics-operator

libs/actions-runner-controller/config.jsonnet
- this includes some new functionality such as:
- allowing modification of var-run mount maximum size limit
- allowing more Docker config options
=> feat(actions-runner-controller): update the legacy ARC

libs/external-secrets/config.jsonnet
Consider this a stupid question or start for discussion... unless, of course, you immediately think this is acceptable...
**Problem** (perhaps minor, but ...)
The manual handling/inputting of a growing list of crd urls irks me a bit when things start growing like such a project like external-secrets have done lately ...
Should the tooling expand to either fetch certain things remotely, it could even run `kustomize build` on those projects that use it?
Or is vendoring a way to go, as long as it's not copying the entire upstream? It grows, gets messy and noisy.
- `vendir` can be used... or jsonnet-bundler's `jb --single` vendoring? 
I'm hesitant to add more files like this to external-secrets, because the structure of a `config.jsonnet` file and basically nothing else is *clean* ❤️. But I'm …
=> feat(external-secrets): v0.15.1

.github/workflows/main.yml, libs/upbound-provider-opentofu/config.jsonnet
ref: https://marketplace.upbound.io/providers/upbound/provider-opentofu/v0.2.3
This provider is replacing the provider-terraform.
I'm creating a separate repo/lib for this instead of further overloading the crossplane project.
=> feat: generate library for upbound's provider-opentofu

libs/pyrra/config.jsonnet
Updates Pyrra to add 0.8 version.
=> pyrra: Add version 0.8

libs/argo-cd/config.jsonnet
Updated library versions to match latest supported [releases](https://github.com/argoproj/argo-cd/releases)
=> argo-cd: supported versions updated

libs/secrets-store-csi-driver/config.jsonnet
[Changelog](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.5.1)
=> Add secrets-store-csi-driver v1.5.1
