- extensions/kausal-shim.libsonnet
This implementation allows both:
* resource.new()
* resource.new('string')
It will allow us to refactor our code gradually.
> fix(kausal-shim): make new() forward compatible

- custom/list.libsonnet
/kind feature
Fixes: #9 
This PR adds the core.v1 List object. This object can be used to combine multiple dissimilar  kubernetes objects into a single object.
> Added core.v1 List Functions

- custom/core/core.libsonnet
Backwards compatible with ksonnet.
ref: https://github.com/grafana/jsonnet-libs/pull/351
> fix(custom): name is optional for persistentVolume

- README.md
- config.yml
Cloning the repo as-is and running it causes a crash, since the extensions/core directory is not present.
> Add 1.21, add empty directory to avoid nil dereference crashes.

- .github/workflows/main.yml
- Makefile
- jsonnet/github_action.jsonnet
- jsonnet/terraform.jsonnet
- scripts/gen.sh
This is a workaround for a bootstrapping problem.
The Github pages configuration can't be applied if the branch does not exist yet. Possible
future solution: https://github.com/integrations/terraform-provider-github/issues/782
> fix(github-action): set gh-pages info in follow up step

- jsonnet/terraform.jsonnet
This is similar to `helm-plugin`, it adds an easy way to find jsonnet libraries through
the Github search.
> style: use singular label

- libs/k8s/README_root.md.tmpl
- libs/k8s/config.jsonnet
- k8s-libsonnet uses the main branch, `jb` defaults to master
- this PR will limit the search to the latest version, hopefully making the search more
deterministic
> fix: jb install branch name + improved search

- libs/k8s/config.jsonnet
Specifically `APIService` kinds are scoped under the `io.k8s.kube-aggregator.pkg.apis.*` path.
> Include resource kinds that are not under the standard regex path.

- jsonnet/terraform.jsonnet
- libs/argo-workflows/config.jsonnet
Turns out that there's already a full json schema in the argo-workflows repo: https://github.com/argoproj/argo-workflows/blob/master/api/jsonschema/schema.json
No need to do the k3s stuff
> Generate full library for `argo-workflows`

- .github/workflows/main.yml
- libs/consul-k8s/config.jsonnet
- libs/consul/config.jsonnet
Split on whether to name this just `consul` or `consul-k8s`
Hashicorp seem to be consolidating all of the their Kubernetes related 'stuff' into the consul-k8s repo so I've gone with that too
> Add consul-k8s

- pkg/builder/objects.go
- pkg/model/modifiers.go
This adds import as a reserved keyword and widens the `-` restriction to contains instead of prefix.
With these changes, the generator can successfully generate jsonnet bindings for OpenShift 4
> fix: add more reserved names to token escaping

- libs/k8s/config.jsonnet
Right now the oldest supported release on Public Clouds is 1.18 (AWS) -> cleanup the older releases
Signed-off-by: Matthias Riegler <matthias.riegler@traefik.io>
> feat: add Kubernetes 1.23 & remove legacy versions

- .github/workflows/main.yml
- README.md
- libs/cluster-api-provider-aws/config.jsonnet
- libs/cluster-api/config.jsonnet
- scripts/gen.sh
This adds jsonnet libraries for:
- [cluster-api](https://github.com/kubernetes-sigs/cluster-api)
- [cluster-api-provider-aws](https://github.com/kubernetes-sigs/cluster-api-provider-aws)
In addition it filters the provided manifests (CRDs) to only apply CRDs to the cluster.
> Add Cluster API + AWS Provider templates, improve applying CRDs on generation step

- scripts/gen.sh
Large CRD manifests (looking at you kube-prometheus) can cause an error like this when applied:
```
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
This commit modifies `gen.sh` to use server-side apply, which doesn't have this problem.
> Use server-side apply

- Dockerfile
- libs/crossplane/config.jsonnet
This PR reduces the number of crossplane libs being rendered to only the latest minor
version.
It also fixes the Dockerfile so a local render of a library works again, mktemp was
failing as the local users did not have write permission.
> fix(ci): master build is failing

- .github/workflows/main.yml
- libs/zalando-postgres-operator/config.jsonnet
The CRDs are taken from the tag with the highest patch version for each
minor version. Versions older than v1.6 use the older deprecated v1beta1
CRDs and have some CRDS missing or at different places in the repo and
have therefore been omitted for simplicity
> Add zalando-postgres-operator v1.6 and v1.7

- pkg/builder/objects.go
- pkg/model/modifiers.go
Before this change, it was not possible to generate libraries that had a
valid "null" OpenAPI key in their CRD.
We fix this by escaping correctly the reserved word 'null'.
There are no tests in this PR, please advise on how to correctly add them.
Fixes #116
> Fix null as key escaping

- libs/calico/config.jsonnet
- libs/cnrm/config.jsonnet
- libs/istio/config.jsonnet
Separate lib updates from #119 to verify diff.
These libs had CRDs based on the deprecated `apiextensions.k8s.io/v1beta1`. The calico
also had a minor issue with a duplicate field that was resolved in a patch, also the CRDs in new versions got moved.
> chore: update libs

- libs/k8s/config.jsonnet
The previous group selector excluded the meta structures which are contained under "io.k8s.apimachinery.pkg.apis.meta". As a result, some very widely used substructures (e.g. labelSelector #124 ) were not included in the libsonnet output. 
P.S.: I couldn't find the "kube-aggregator" group in the current swagger.json, is that still used?
> k8s-libsonnet: include apimachinery meta structures

- libs/crossplane/config.jsonnet
- Add crossplane 1.7 from release 1.7.0
- Bump crossplane 1.6 to release 1.6.4
- Bump provider-kubernetes to release 0.3
> feat(crossplane): Add helm-provider and  bump multiple versions

- libs/crossplane/config.jsonnet
The nested 'grafana.grafana' doesn't include the providerConfig, I'll probably propose upstream to eventually drop the repeated nesting.
> fix(crossplane/grafana): include providerConfig

- libs/crossplane/config.jsonnet
The recently added helm-provider for crossplane was added in version
0.10, however the output-path was incorrectly set to version "10.0".
This commit corrects that oversight
> chore(crossplane/provider-helm): Fix typo in published version

- .github/workflows/main.yml
- libs/contour/config.jsonnet
I feel that [Project contour](https://projectcontour.io/) is an important CNCF member which deserves to be included in `jsonnet-libs` collection of generated libraries.
>NOTE: I could not generate versions prior to `1.9.0`,  as the generator crashes with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x95e582]
goroutine 1 [running]:
github.com/jsonnet-libs/k8s/pkg/swagger.(*CRDLoader).Load(0x7f19ef591418, {0xc00052c000, 0xc0006bc330, 0x1})
/app/pkg/swagger/crd.go:52 +0x582
github.com/jsonnet-libs/k8s/pkg/swagger.Load({0xb2b540, 0xc00000e0d8}, {0xc000074840, 0x1})
/app/pkg/swagger/load.go:23 +0x90
main.main.func1(0xc0000694c0, {0xc00002cd00, 0x0, 0x4})
/app/main.go:62 +0x554 …
```
> added contour to generated libs

- libs/k8s/custom/core/apps.libsonnet
The extensions/v1beta1 API was removed in Kubernetes v1.22. The patch
that adds documentation for that API shouldn't be applied if the API
doesn't exist.
Fixes #132.
> Remove k8s-libsonnet extensions patch in >= 1.22

- libs/crossplane/custom/crossplane/resource.libsonnet
As explained here, writeConnectionSecretRef is required to properly propagate the
connectionDetails to Secrets downstream. This ensures it is set when connectionDetails are
added.
> feat(crossplane): set writeConnectionSecretRef when adding connectionDetails

- libs/crossplane/custom/crossplane/resource.libsonnet
To do this here, the function below needs access to the attributes in `super`.
> fix(crossplane): set writeConnectionSecretRef when adding connectionDetails

- libs/argo-workflows/config.jsonnet
This additionally contains a minor refactor to reduce duplication in the jsonnet
for Argo Workflows to allow easier addition of versions in future.
> Add version 3.3 of Argo Workflows

- libs/kubevela/config.jsonnet
sorry for the last PR. the prefix was incorrect. In addition, dev_healthscopes produce incorrect output, disable for now.
> fix: generate correct kubevela libsonnet

- libs/kube-prometheus/config.jsonnet
- libs/kube-prometheus/custom/monitoring/endpoint.libsonnet
- libs/kube-prometheus/custom/monitoring/pod_metrics_endpoint.libsonnet
- libs/kube-prometheus/custom/monitoring/relabel_config.libsonnet
Add helpers to kube-prometheus for defining endpoints for Prometheus to
scrape and relabel_configs.
> Add helpers to kube-prometheus

- libs/kubevela/config.jsonnet
- pkg/builder/objects.go
- pkg/model/gvk.go
- pkg/model/modifiers.go
This PR aims to get a meaningful code generation from kubevela while remaining backward-compatibility. Two improvements are contained:
- I included all the reserved keywords of jsonnet for id escape in order to get the transpilation  passed. (see https://jsonnet.org/ref/spec.html)
- I found nested object types in array (see example below) are not resolved. this makes the generated kubevela jsonnet useless because 90% of the definitions are ignored. So I added the corresponding logic to generate jsonnet code in this case.
eg. given the crd yml snippet below
```yaml
spec:
description: ApplicationSpec is the spec of Application
properties:
components:
items:
description: ApplicationComponent describe the component of application
properties:
name:
type: string
traits:
description: Traits …
```
> feat: support nested object types in array

- libs/contour/config.jsonnet
- added contour version 1.21 `v1.21.1`
- updated 1.20 to latest patch `v1.20.2`
> [contour-libsonnet] added contour version 1.21 and updated 1.20 to latest patch

- .github/workflows/main.yml
- libs/kubernetes-secret-generator/config.jsonnet
Libraries for the few CRs in the [Kubernetes Secret Generator](https://github.com/mittwald/kubernetes-secret-generator) controller.
There's also something that watches annotations on secrets, but to the best of my knowledge there's no real way (or reason) to generate anything for that, so this is just for the custom objects.
> Add: kubernetes-secret-generator

- pkg/model/modifiers.go
Blame on you, @aiven :D
They have e.g. this in one of their CRDs:
```
pg_partman_bgw.interval:
description: pg_partman_bgw.interval Sets the time interval
to run pg_partman's scheduled tasks
format: int64
maximum: 604800
minimum: 3600
type: integer
```
There's no diff for libraries that are not using it
> fix: allow `.` to be part of modifiers

- libs/strimzi/config.jsonnet
Adding [version 0.32.0 of the strimzi crds](https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.32.0).
> chore(strimzi): generate version 0.32.0

- libs/crossplane/config.jsonnet
The old terrajet version was dumped, so we're back to 0.0 It's now on the upbound marketplace: https://marketplace.upbound.io/providers/grafana/provider-grafana/v0.0.7 
https://github.com/grafana/crossplane-provider-grafana
> Update Grafana crossplane library to newest version of provider

- libs/crossplane/config.jsonnet
There's currently three: AWS, GCP and Azure
They are going to be the most updated providers for each CSP: https://blog.upbound.io/first-official-providers/
> Crossplane: Add official Upbound providers to the list

- libs/kube-prometheus/config.jsonnet
I used the release branch instead of the tag because the project [recommends using the branch][1], but I can change it.
[1]: https://github.com/prometheus-operator/kube-prometheus/releases/tag/v0.11.0
> Add kube-prometheus 0.11 CRDs

- libs/k8s/custom/core/core.libsonnet
This allows for users to keep all environment variables in the same place and allows for easy overrides.
I know there already exist helpers like `fromSecretRef` but this would simplify reusable modules quite a bit.
For example, one could have
```
myCoolContainer(extraEnv) :: container.new(...) + container.withEnvMap({
'SOME_DEFAULT': {secretKeyRef: { name: 'key', foo: 'bar' }}
} + extraEnv)
```
which would then allow the consumers of this container to override it with a static string or a custom secret without having to use `container.withEnv` directly
> feat: allow for non-string values in withEnvMap

- libs/secrets-store-csi-driver/config.jsonnet
- libs/secrets-store-csi-driver/custom/secrets-store-csi-driver/secretProviderClass.libsonnet
This adds some very handy helper functions to use the Secrets-Store CSI Driver with Azure Kubernetes Service (AKS).
It can also be used as template for other Secret-Store CSI Driver implementations (like HashiCorp Vault or AWS)
> feat(secret-store-csi-driver): add azure specific helper functions

- libs/k8s/config.jsonnet
Codegen works, not sure if search should be excluded for 1.26, as well.
Resolves #238
Requires [k8s-libsonnet#1](https://github.com/jsonnet-libs/k8s-libsonnet/pull/1)
> Added Kubernetes 1.26 version

- .github/workflows/main.yml
- jsonnet/github_action.jsonnet
We're running into api limits on github actions, reducing the number of steps in the
pipelines should prevent that.
> feat: reduce pipelines steps with paths-filter

- libs/crossplane/config.jsonnet
Update several libraries:
- Add Crossplane 1.10
- Remove unsupported Crossplane 1.7
- Update contrib providers
- Update Grafana provider
- Replace provider-terraform with the upbound official one
- Remove terrajet based providers in favor of the upbound official providers
- Update upbound official providers
This PR also restructures the file a bit.
This PR replaces #263
> chore(crossplane): update libraries

- libs/vertical-pod-autoscaler/custom/core/autoscaling.libsonnet
Add a `withTargetRef` patch to the VerticalPodAutoscaler to set the `spec.targetRef` field to the given object, mirroring the `withScaleTargetRef` patch applied to the HorizontalPodAutoscaler.
> feat(vertical-pod-autoscaler): add withTargetRef patch

- libs/crossplane/config.jsonnet
The upbound provideres weren't generated properly, this was due to doc.crds.dev not being
aware of the new versions and returning an empty/error response. The new versions get
generated when visited through a browser.
This should probably be checked for and returned with an error in the code, but I haven't
had time to look why that isn't happening.
> fix(crossplane): generate upbound providers properly

- libs/keda/config.jsonnet
Similar to https://github.com/jsonnet-libs/k8s/pull/254 but with the most recent versions.
> chore(keda): add 2.8 and 2.9 versions

- libs/k8s/custom/core/mapContainers.libsonnet
- libs/k8s/custom/core/volumeMounts.libsonnet
Currently, `mapContainers` only acts on `containers` and not `initContainers`. This add an option to also map `initContainers`.
I am open to an alternative of adding separate `mapInitContainers` help methods, however, this seems most user friendly. 
An example of where this would be useful is here: https://github.com/jsonnet-libs/k8s/blob/450a1f2a0d89d90faad2fc1eef7b8654d8daeab4/libs/k8s/custom/core/volumeMounts.libsonnet#L76-L95
It seems likely that when mounting volumes one probably wants to also mount them to `initContainers` as copying data from `initContainers` to `containers` is a fairly common pattern.
Closes #223
> Allow `volumeMount` helpers to optionally act on `initContainers`

- libs/crossplane/custom/crossplane/resource.libsonnet
These are helper functions for the functions described here: https://docs.crossplane.io/v1.9/reference/composition/#patch-types
> Crossplane: Add `combineFromComposite` and `combineToComposite` patches

- libs/crossplane/custom/crossplane/resource.libsonnet
That transform only works on strings
Also, add a standalone `convert` helper
> Crossplane: Convert to string on `match` transform

- .github/workflows/main.yml
- libs/teleport-operator/config.jsonnet
Adding new jsonnet-lib, teleport-operator 12.2.2. This references the [custom resource definitions in the teleport repo](https://github.com/gravitational/teleport/tree/v12.2.2/examples/chart/teleport-cluster/charts/teleport-operator/templates).
> feat: add teleport-operator 12.2.2

- pkg/model/modifiers.go
From https://github.com/jsonnet-libs/k8s/pull/297. It didn't modify the kubernetes library but it modified lots of others. I'll have to think of a rule to allow the status conditionally
> Revert generating status attributes

- libs/secrets-store-csi-driver/config.jsonnet
- libs/secrets-store-csi-driver/custom/secrets-store-csi-driver/secretProviderClass.libsonnet
* Added 1.3.3 version of secret-store CRD (no changes from 1.2.4)
* added a `withClientId` function, as [Workload Identity](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity) is now out of Preview and in GA for AKS, and the field is need to use a Key Vault with Workload Identity
* Fixed an error in the `objects` rendering (it was expecting an object instead of an array, with the change it passes all render tests now)
> fix for object render and add clientId field for Azure Workload Identity

- .github/workflows/main.yml
- libs/google-cloud-sql-proxy-operator/config.jsonnet
Add the crd for the [google cloud sql operator](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/tree/main). The operator helps configure and inject the gcp cloud sql operator for connecting to gcp mssql, mysql, and postgres database instances.
> feat: add google cloud sql operator

- libs/crossplane/custom/crossplane/resource.libsonnet
`fallbackTo: Input` and clamp math functions were added and these are helpers to make them easier to use
They are documented here: https://docs.crossplane.io/latest/concepts/composition/#transform-types
> Crossplane: Support 1.12 transforms

- libs/contour/config.jsonnet
This PR adds Contour v1.25 and updates the existing versions with the latest available tag based on the [compatibility matrix. ](https://projectcontour.io/resources/compatibility-matrix/)
> add Contour v1.25 and bump versions to the latest available tag

- libs/argo-cd/config.jsonnet
Add versions `2.6.11` and `2.7.6` for argo-cd.
> Add new minor versions for argo-cd

- libs/prometheus-operator/config.jsonnet
Adds all current minor versions of the prometheus-operator. This change also introduces two new CRDs, `prometheusagents` which was added in `0.64` and `scrapeconfigs` which was added in `0.65`. The current implementation in this repo handles `404` gracefully and simply does not generate for the new CRDs if they cannot be downloaded. I'm not sure if this is intended but since it works I opted to just include the new CRDs for all version. Let me know if you rather want me to build logic for this in the `config.jsonnet` file.
> Add new prometheus-operator versions

- libs/teleport-operator/config.jsonnet
Adds:
- 13.0 (from 13.0.4)
- 13.1 (from 13.1.5)
- 13.2 (from 13.2.3)
This brings in a couple new resources:
- teleportprovisiontokens.resources.teleport.dev (added in 13.0)
- teleportoktaimportrules.resources.teleport.dev (added in 13.2)
> Update teleport-operator versions

- libs/crossplane/config.jsonnet
https://github.com/crossplane-contrib/provider-nop/releases/tag/v0.2.0
> Bump Crossplane provider-nop to v0.2.0

- libs/secrets-store-csi-driver/custom/secrets-store-csi-driver/secretProviderClass.libsonnet
There is a tiny typo in the SecretProviderClass custom function "withClientId". The azure operator is specifically asking for `clientID` rather than `clientId`. 
Adding the wrong casing results in the following error:
```
secrets-store E0804 16:23:24.908716       1 reconciler.go:223] "failed to reconcile spc for pod" err="failed to rotate objects for pod ***, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to create auth config, error: could not find clientid in secrets(map[])" spc="***" pod="***" controller="rotation"
```
The parameters are not defined in the CRD and therefore vulnerable to typos.
> Fix SecretProviderClass typo

- libs/cloudnative-pg/config.jsonnet
This PR updates the library by adding the latest [v1.20.2](https://github.com/cloudnative-pg/cloudnative-pg/releases/tag/v1.20.2) release of the CloudNative PG operator.  It also includes all versions that are documented on the [CNPG documentation](https://cloudnative-pg.io/docs/).
> Bump CloudNative PG operator to v1.20.2

- libs/actions-runner-controller/config.jsonnet
This one is a bit of an awkward update.
I'm not convinced this is the best way so happy to change it
The actions-runner-controller has been adopted by GitHub officially, along with a new 'mode'.
Which is actually a completely independent set of CRDs and controllers, but its all in the same repo.
It's not clear if there will be any significant further development on the 'legacy' mode either.
See the release announcement here: https://github.com/actions/actions-runner-controller/discussions/2775
I've removed all but the last 2 of the 'legacy' versions and just added the new CRDs as `0.4`.
We could make this a new lib, but as always, naming is the hardest bit. 
Given the new 'mode' is still called the Actions Runner Controller i'm not sure what else to call it and renaming the existing lib …
> feat: Add 'runner scale sets' to actions-runner-controller

- .github/workflows/main.yml
- libs/argo-rollouts/config.jsonnet
Generate libsonnet for the argo-rollouts [custom resource
definitions](https://github.com/argoproj/argo-rollouts/tree/v1.6.0/manifests/crds).
[Argo Rollouts](https://argo-rollouts.readthedocs.io/en/stable/) is a progressive
delivery controller that supports advanced deployment patterns such as
blue-green, canary, canary analysis, experimentation, and progressive
delivery for kubernetes.
> feat: add argo-rollouts v1.6.0

- libs/crossplane/config.jsonnet
They can still be pulled by jsonnet-bundler by pointing to an old changeset 
Generating the Crossplane provider libs is pretty long
> Crossplane: Upgrade Grafana + Clear out old versions

- libs/eck-operator/config.jsonnet
This PR updates the CRD path and updates the available versions.
> fix: the CRD path for ECK Operator and update the available versions

- libs/traefik/config.jsonnet
This PR adds additional new Traefik libraries. From the v2.9.10 Traefik introduces the new prefix for all CRDS, that PR takes that into account and creates library for the old CRD versions and the new ones as well.
> update Traefik library by adding new versions 

- libs/traefik/config.jsonnet
See the release notes for [Traefik](https://github.com/traefik/traefik/releases/tag/v2.10.5) and [Traefik Helm Chart. ](https://github.com/traefik/traefik-helm-chart/releases/tag/v25.0.0)
> bump Traefik libsonnet to v2.10.5

- libs/grafana-operator/config.jsonnet
`grafanadashboard` CRD is invalid in versions v5.1, v5.2 and v5.3, so I had to skip these (more info in the PR https://github.com/jsonnet-libs/k8s/pull/336). 
The issue was fixed in https://github.com/grafana-operator/grafana-operator/pull/1199 so we can safely add v5.4
> chore(grafana-operator): add 5.4 version

- libs/crossplane/custom/crossplane/resource.libsonnet
To avoid diffs in ArgoCD, this commit adds the transform string type explicitly
> fix: add missing value to Crossplane resource patch

- pkg/swagger/load.go
Allow loading the CRD data from a local file instead of a URL. If the URI passed is a URL, then use the original mechanism, but if not then try to interpret it as a local file instead.
This is useful if you want to use k8s-gen with libraries that do not make the CRDs available via a simple endpoint, and which require downloading and processing locally before passing to k8s-gen.
> Allow loading CRD data from local file

- .github/workflows/main.yml
- libs/emissary/config.jsonnet
This adds libraries for the [Emissary ingress](https://github.com/emissary-ingress/emissary) (previously named Ambassador in CNCF incubation), and is built on Envoy.
> Emissary ingress libraries

- jsonnet/config.jsonnet
- jsonnet/files/mkdocs.css
- jsonnet/mkdocs.jsonnet
This ports back the improvements introduced in Grafonnet, this layout
seems to work well.
> style: update mkdocs config and css

- libs/karpenter/config.jsonnet
Karpenter CRDs have changed [significantly](https://karpenter.sh/docs/upgrading/v1beta1-migration/#upgrade-procedure) in 0.32
0.31 is the only version supporting downgrades from 0.32 and 0.33 is the latest!
> feat(libs/karpenter): add/remove versions

- libs/argo-cd/config.jsonnet
It also removes ArgoCD 2.2 and 2.3.
> Add argo-cd 2.10 and 2.11

- libs/cloudnative-pg/config.jsonnet
It should fix the issue with building the latest CNPG version.
> Fix: add missing comma  and let the CNPG v1.23.1 to be built

- libs/rabbitmq-messaging-topology-operator/config.jsonnet
Add missing new versions from RabbitMQ messaging topology operator.
I tested the generation locally and works without error and the produced libs are in-sync with the upstream operator.
Trailing coma and single quotes are changes made by the linter, let me know if they should be reverted.
> feat: Update rabbitmq-messaging-topology-operator libs

- libs/edp-keycloak-operator/config.jsonnet
This commit adds all versions of the edp keycloak operator from version 1.18.2
to 1.22.0.
> feat(edp-keycloak): add version until 1.22.0

- libs/gateway-api/config.jsonnet
A new version of the Kubernetes Gateway API has been released (v1.1.0).
Also, it has been noted that [experimental versions](https://gateway-api.sigs.k8s.io/concepts/versioning/) of the API have not been included in the jsonnet-libs releases up until now.
1. Add support for v1.1.0
2. Add experimental release for all existing versions up to and including the latest v1.1.0
> feat: Add k8s gateway api v1.1 and all experimental versions

- .github/workflows/main.yml
- jsonnet/github_action.jsonnet
Update the used actions to their latest major version, the jobs started failing because upload-artifacts@v2 has been deprecated.
> chore: update github actions

- libs/cloudnative-pg/config.jsonnet
That PR updates the CloudNativePG library to the latest supported versions: [v1.24.0](https://cloudnative-pg.io/documentation/1.24/) and [v1.23.4.](https://cloudnative-pg.io/documentation/1.23/)
> Bump CloudNativePG libsonnet

- libs/datadog-operator/config.jsonnet
Simple version bump to v1.8.0 released CRDs.
> feat: datadog-operator v1.8.0 with DatadogPodAutoscaler CRD

- libs/crossplane/config.jsonnet
Bump Upbound Provider AWS to v1.6.1
This PR should add v1beta2 CRDs
URL validation: https://doc.crds.dev/github.com/crossplane-contrib/provider-upjet-aws@v1.6.1
> Bump Upbound Provider AWS to v1.6.1

- libs/datadog-operator/config.jsonnet
Version bump to v1.9.0 released CRDs.
> feat: datadog-operator v1.9.0 with DatadogDashboards CRD

- libs/crossplane/config.jsonnet
Merging a not rebased branch kept this entry around, removing it.
> fix(crossplane): remove not-working upbound-provider-aws

- libs/crossplane/Makefile
Fix a typo in the generation script. No-op since previously the CRD list was generated for v1.7.0 and in v1.8.3 no change happened.
> Fix Upbound CRD generation Makefile

- libs/milvus-operator/config.jsonnet
* Now uses the full semver since the CRD changes between patch versions.
* Changed `0.9.15` to `0.9.11` since that was when the change was introduced.
* Added latest and interim versions.
> Add new milvus-operator CRD versions

- libs/crossplane/config.jsonnet
This PR adds CRDs for inputs for two crossplane functions:
- [function-patch-and-transform](https://github.com/crossplane-contrib/function-patch-and-transform)
- [function-cel-filter](https://github.com/crossplane-contrib/function-cel-filter)
> Add CRDs for functions patch-and-transform and cel-filter

- libs/teleport-operator/config.jsonnet
This adds support for `teleport-operator` version `16.4.8` and references an updated CRD path.
> feat(teleport-operator): add version `16.4.8`

- .github/workflows/main.yml
- libs/crossplane-core/config.jsonnet
- libs/crossplane-core/custom/crossplane/compositeResourceDefinition.libsonnet
- libs/crossplane-core/custom/crossplane/composition.libsonnet
- libs/crossplane-core/custom/crossplane/resource.libsonnet
The crossplane-libsonnet repository has grown quite big is struggling.
* The mkdocs site can't get rendered because the search index is too big
* jsonnet-bundler install takes a long time to download the GitHub archive
* the k8s CI job takes a lot of time, just a matter of time before that starts timing out on the free nodes
This only splits of a bit, follow up PRs needed to split off the others, after all providers are in separate repos, I supposse we can archive the original repo (keeping it available for people depending on it but not updating).
> feat(crossplane): split off core libs into separate repository

- libs/argo-cd/config.jsonnet
Add the CRDs for ArgoCD v2.12 and v2.13. Also update the patch versions of previous releases.
> Add ArgoCD versions 2.12 and 2.13

- libs/crossplane-core/config.jsonnet
This PR adds crossplane core v1.18, with function-status-transformer v0.4 and function-go-templating v0.9.
> Bump crossplane core to 1.18 and functions

- libs/cloudnative-pg/config.jsonnet
The PR adds a new version for the CloudNative-PG operator. See the [docs](https://cloudnative-pg.io/docs/).
> Bump CNPG library to v1.25.0

- libs/argo-cd/config.jsonnet
This PR reduces the number of supported argo-cd versions.
> Only the three most recent minor versions are eligible for patch releases. Versions older than the three most recent minor versions are considered EOL and will not receive bug fixes or security updates.
Source: https://argo-cd.readthedocs.io/en/stable/developer-guide/release-process-and-cadence/#patch-releases-eg-25x
> chore(argo-cd): reduce to supported versions

- libs/traefik/config.jsonnet
hopefully fixes #507 
Tested this on my local jsonnet repositories and it worked as expected. But please double-check ;)
> feat(traefik): add latest 2.x and 3.x versions

- libs/strimzi/config.jsonnet
solves https://github.com/jsonnet-libs/k8s/issues/521
Add support for strimzi up to v0.45 and remove support for 0.3x which has the latest release for 0.39 in 2023.
> feat(strimzi): remove 0.3x versions; add versions up to 0.45

- libs/crossplane/config.jsonnet
This PR adds CRDs for inputs for the crossplane [function-kcl](https://github.com/crossplane-contrib/function-kcl)
> Add CRDs for function-kcl

- libs/cnrm/config.jsonnet
Is a big jump, but at this point I don't think it matters if we don't include all or part of the versions in between.At least, whoever wants to use latest version would be able to do so.
> feat: Generate for latest CNRM version (1.130.2)

- libs/zalando-postgres-operator/config.jsonnet
solves #525 
- remove all versions (>2y old), but keep v1.8 for compatibility
- add v1.11-v1.14
> Upgrade zalando operator

- Dockerfile
- libs/fluxcd/config.jsonnet
Had to pin go-jsonnet to 0.20.0 while current PRs upgrading to go 1.21/1.23 and go-jsonnet 0.21.0 are merged
> Add Flux 2.6.0/2.6.1 libs

- libs/litmus-chaos/config.jsonnet
Extend `litmus-chaos` functionality to support chaos_scheduler crd that is needed to create scheduled chaos tests. https://github.com/litmuschaos/chaos-scheduler/tree/master/deploy/crds
> litmus-chaos: update to latest version & introduce chaosscheduler_crd..yaml

- libs/litmus-chaos/config.jsonnet
Use latest version for:
- chaos-operator  crds: https://github.com/litmuschaos/chaos-operator/releases/tag/3.20.0
- chaos-scheduler crd : https://github.com/litmuschaos/chaos-scheduler/releases/tag/3.20.0
> litmus-chaos: bump version to 3.20.0

- libs/istio/config.jsonnet
since istio: crd-all.gen.yaml moved from `crds` to `files` since 1.24
Before Istio 1.24, the location as below:
https://raw.githubusercontent.com/istio/istio/1.17.6/manifests/charts/base/crds/crd-all.gen.yaml
https://raw.githubusercontent.com/istio/istio/1.23.3/manifests/charts/base/crds/crd-all.gen.yaml
but moved from `crds` to `files` since 1.24
https://raw.githubusercontent.com/istio/istio/1.24.5/manifests/charts/base/files/crd-all.gen.yaml
https://raw.githubusercontent.com/istio/istio/1.25.2/manifests/charts/base/files/crd-all.gen.yaml
> istio: crd-all.gen.yaml moved from crds to files since 1.24
